### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by syota0612** [syota0612/chat-space#10]
# IPアドレス
3.115.190.20

**Comment by kohei-isoda** [comment]
近藤さん、ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by syota0612** [comment]
ご確認ありがとうございます。

３点ほど挙動について質問なのですが
・アラートが出た後に投稿ボタンを押してもアクションが起きない。
・グループに他のユーザーを追加ご同じユーザーを登録できてしまう。また登録した分だけグループ投稿画面のメンバーに追加されてしまう。
・画像投稿で投稿できない画像がある。(調べたら投稿できる画像ファイルサイズの設定にひっかかている、または拡張子がパソコンでは対応していない画像であるという仮説に至りました。)

この３点についてはカリキュラムの範囲外という認識でいいのでしょうか？

**Comment by kohei-isoda** [comment]
ご質問ありがとうございます！

> アラートが出た後に投稿ボタンを押してもアクションが起きない。
> グループに他のユーザーを追加後同じユーザーを登録できてしまう。また登録した分だけグループ投稿画面のメンバーに追加されてしまう。
上記2点は工夫次第で修正の余地があります！
（※ ただ、今回は基準として設けておりません）

> 画像投稿で投稿できない画像がある
こちらはEC2のt2.microという最小サイズのインスタンスを使用していますので、
近藤さんが仰っている「画像ファイルサイズの設定にひっかかっている」の仮説が正解です！

**Comment by syota0612** [comment]
お忙しい中ご返信いただきありがとうございます。
できるだけより良くできるよう調べてみます。
ありがとうございました。
